Task4 dynamic connectivity
vladislav-miroshnikov/high-performance-graph-analysis-course pull request #4
Opened 2022-05-17 19:41 UTC by vladislav-miroshnikov

2022-05-17 20:43 UTC, katyacyfra requested changes
1. В противном случае будет образовываться новая компонента связности. --- нужно ли выполнить в этом случае какие-либо действия?
2. В случае, если BFS-дерево почти вырождается в список... -- это как? Привидите пример графа, для которого такое возможно.
3. Обработка одной вершины внутри рекурсивной процедуры fall(n) занимает O(deg(n)) времени --- почему? Напишите подробнее

2022-05-18 19:35 UTC, vladislav-miroshnikov commented
> В случае, если BFS-дерево почти вырождается в список... -- это как? Привидите пример графа, для которого такое возможно.

Например, в вырожденном случае может оказаться, что все левое дерево пусто на каждом уровне и есть только правые деревья (или ситуация наоборот), то в таком случае дерево выродиться в список. Если говорить не про граф, а в целом, то такое может быть, если исходная последовательность упорядочена по возрастанию или убыванию ключей, то мы получим в итоге список.
Если говорить про нашу задачу, то BFS-дерево почти вырождается в список в случае графа, как на фото:
<img width="134" alt="image" src="https://user-images.githubusercontent.com/55508043/169138698-e96856e2-a9c9-492c-b95b-53a64044b653.png">
При этом BFS дерево будет следующим (в данном случае совпадет по виду с исходным графом)
<img width="191" alt="image" src="https://user-images.githubusercontent.com/55508043/169139155-656188d7-51eb-4293-a8c6-de7b22311c28.png">
А высота такого "почти" списка сравнима с n (то есть почти n), где n - кол-во вершин графа.

2022-05-18 19:44 UTC, vladislav-miroshnikov commented
> В противном случае будет образовываться новая компонента связности. --- нужно ли выполнить в этом случае какие-либо действия?

В файле расписал один случай. Случай, если у нас только одна фиксированная вершина-источник s и никаких других больше нет. Однако я приведу и другой случай здесь. На самом деле, если вспомнить лекцию, то мы могли бы хранить что-то в духе леса остовных деревьев, только лес BFS деревьев, по BFS дереву на каждую компоненту связности. И в таком случае если посмотреть на пример ниже (вершина s это вершина с номером 1)
<img width="264" alt="image" src="https://user-images.githubusercontent.com/55508043/169142715-3bd80419-8d0d-4721-8c8c-540238b1d847.png">
То при удалении ребра 1-4 у нас бы образовалась новая компонента связности (поддерево с вершиной 4) и данная вершина 4 была бы еще одной вершиной-источником и мы могли бы запросу по вершину-источнику определять, в какое BFS-дерево нам нужно идти. Или можно было бы хранить деревья в каком-нибудь ассоциативном массиве или другой структуре данных.

2022-05-19 20:18 UTC, katyacyfra approved these changes
Ок. 5 баллов (половина баллов, т.к. исходное решение очевидно позаимствововано у другого студента)

2022-05-30 14:15 UTC, katyacyfra requested changes
1. Теперь рассмотрим цикл C = (C1 ∪ C2) (C1 ∩ C2) --- что это за цикл? Выражение математически некорректное, какой-то знак пропущен между скобками?Запахло бездумным копипастом... Почему мы рассматриваем именно такой цикл? 
2. Раз Вы ссылаетесь на статью, расскажите кратко основную идею доработки алгоритма до поддержки полностью динамического остовного леса мнимального веса (секция 5). Только своими словами, а не копипастом теорем с переводом на русский.

2022-05-30 15:44 UTC, vladislav-miroshnikov commented
> Теперь рассмотрим цикл C = (C1 ∪ C2) (C1 ∩ C2) --- что это за цикл? Выражение математически некорректное, какой-то знак пропущен между скобками?Запахло бездумным копипастом... Почему мы рассматриваем именно такой цикл?

Объединение позволяет сформировать цикл, в котором содержатся ребра e1 и e2. Это нужно, чтобы показать, что так как ребро е2 имеет самый большой вес, а значит по инварианту самый низкий уровень в этом цикле, а значит, что его уровень меньше, чем у е1. Удаление пересечения циклов C1 и C2 из объединения нужно, чтобы убрать из рассмотрения ребро е, которое удалилось из графа и самого остовного дерева. Вот на примере ниже минимальное остовное дерево. Представим, что ребро e удалилось, объединение циклов C1 (1-2-8-7-3-1) с C2(7-8-10-11-7) добавит ребра e1 и е2 в рассмотрение, а разность удалит  ребро е.

<img width="374" alt="4_2" src="https://user-images.githubusercontent.com/55508043/171025971-4a5c0dd0-865f-456b-96c7-bfcf910b6c70.png">

2022-05-30 15:45 UTC, vladislav-miroshnikov commented
> Раз Вы ссылаетесь на статью, расскажите кратко основную идею доработки алгоритма до поддержки полностью динамического остовного леса мнимального веса (секция 5). Только своими словами, а не копипастом теорем с переводом на русский.

Секция 3 рассматривает задачу декрементальной динамической связности, но в ином виде, секция 4 же описывает, как сделать алгоритм миним остовного дерева, но при этом имея другой порядок обхода уровней. Основная причина этого в том, что в статье уровни увеличиваются начиная с 0, а в нашей задаче понижаются начиная с log. От этого многие утверждения в статье меняются, как и инвариант. Если говорить про секцию 5, то честно скажу, я ее не читал, так она не требуется для выполнения поставленной задачи и не совсем относится к ней.

2022-05-30 18:10 UTC, katyacyfra approved these changes
Ок. Можно построить два варианта алгоритма с понижением уровней, как в лекции/ либо с повышением, как в статье. Оба варианта корректны, но условие задачи я не особо хорошо сформулировала, это да. Поэтому 10 баллов.

2022-08-20 14:07 UTC, merged