Task5 dynamic tc
vladislav-miroshnikov/high-performance-graph-analysis-course pull request #5
Opened 2022-05-19 19:29 UTC by vladislav-miroshnikov

2022-05-20 09:19 UTC, katyacyfra requested changes
Сам алгоритм и корректность ок. Вызывает сомнения оценка сложности.
Вы утверждаете, что на каждый вызов удаления ребра Вы запустите DFS, отсюда сложность m(n+m). Это правда для строчки 4, но сколько раз будет вызвана строчка 6?
В худшем случае, вершин, соответствующих условию в строчке 5, может быть порядка n, тогда на одно удаление ребра у Вас уже O(n) вызовов DFS...

2022-05-20 14:04 UTC, vladislav-miroshnikov commented
Да, действительно, оценка не совсем верная, исправил в тексте. Дополнительно отмечу, что строки 5-8 могут выполниться не более n^2 раз (а не n^3 раз) из-за декрементальности алгоритма, так как попав в 6-8 мы занулим хотя бы одну из ячеек матрицы, а их всего n^2 и кол-во единиц может только уменьшаться со временем.

2022-05-20 14:11 UTC, vladislav-miroshnikov commented
То есть соображения такие же, как в инкрементальном алгоритме, где вместо n^3 стало n^2 из-за инкрементальности

2022-05-21 11:19 UTC, katyacyfra approved these changes
Общее рассуждение у Вас верное, но оно слишком общее. Да, действительно, т.к. алгоритм декрементальный, то ячейка станет 0 как минимум один раз за одно удаление.
Хотелось услышать, как это обнуление ячеек (и каких именно!) повлияет на количество вызовов dfs.
Ладно, не буду занудничать, но 3 балла всё-таки сниму, т.к. вся мякотка в этой задаче именно доказать оценку сложности. 7 баллов. Пофикшено, 10 баллов.

2022-08-20 14:07 UTC, merged